#!/usr/bin/env bash
wget -O ../raw/106.pdf http://www.easycard.com.tw/Upload/file/1066.pdf
wget -O ../raw/105.pdf http://www.easycard.com.tw/Upload/file/1055.pdf
wget -O ../raw/104.pdf http://www.easycard.com.tw/Upload/file/1044.pdf
wget -O ../raw/103.pdf http://www.easycard.com.tw/Upload/file/1033.pdf
wget -O ../raw/102.pdf http://www.easycard.com.tw/Upload/file/10222.pdf
wget -O ../raw/101.pdf http://www.easycard.com.tw/Upload/file/1011.pdf
wget -O ../raw/100.pdf http://www.easycard.com.tw/Upload/file/1000.pdf
wget -O ../raw/99.pdf http://www.easycard.com.tw/Upload/file/999.pdf
wget -O ../raw/98.pdf http://www.easycard.com.tw/Upload/file/988.pdf
wget -O ../raw/97.pdf http://www.easycard.com.tw/Upload/file/977.pdf
wget -O ../raw/96.pdf http://www.easycard.com.tw/Upload/file/966.pdf
wget -O ../raw/95.pdf http://www.easycard.com.tw/Upload/file/955.pdf
wget -O ../raw/94.pdf http://www.easycard.com.tw/Upload/file/944.pdf
wget -O ../raw/93.pdf http://www.easycard.com.tw/Upload/file/933.pdf
wget -O ../raw/92.pdf http://www.easycard.com.tw/Upload/file/922.pdf
wget -O ../raw/91.pdf http://www.easycard.com.tw/Upload/file/911.pdf
wget -O ../raw/90.pdf http://www.easycard.com.tw/Upload/file/900.pdf
wget -O ../raw/89.pdf http://www.easycard.com.tw/Upload/file/899.pdf
